### ISSUE TITLE
arrow history

### ISSUE THREAD

**Issue by ldd** [ldd/vscode-jq#14]
quoting a user in HN:

> Thanks for your plugin. I wish it had up arrow history. I keep a separate text log with commands and it would be nice if the plugin tracked them. Especially given the high numbers of jq syntax errors.

**Comment by ldd** [comment]
I've resolved this issue in the source code by adding a per-opened-file history of commands.

I think it works very nicely.

[Here's the commit](https://github.com/ldd/vscode-jq/commit/fb324ff938e61e97cc54b7d67fab19d6fd968a67)

I'll try to push a release tomorrow.

**Comment by ldd** [comment]
published to the store as v0.4.0! 
fixed by fb324ff938e61e97cc54b7d67fab19d6fd968a67

**Comment by rehangit** [comment]
Loving this. But can it be improved a bit please. Selecting a history item should select it for further editing. Currently there is no way to incrementally improve the expression as the last/historic one is not editable... one has to retype the whole thing.
