### ISSUE TITLE
Allow viewing non-json files 

### ISSUE THREAD

**Issue by rehangit** [ldd/vscode-jq#17]
There is no benefit in this restriction to strictly require files to be json files: https://github.com/ldd/vscode-jq/blob/31dbb4ae2047f5711e0a658d76a8d6d124d8a9c2/src/commands/showPreview.ts#L13

I would like to view json log files which are multiple json objects per line stored in one file.

The functionality already works but requires me to rename my log files to be .json (which it are not). Just removing the above check should work.

**Comment by ldd** [comment]
You are 100% right. That makes sense.

I'll add an option to turn this off for the next release. 
In the meantime, there is a workaround.
In your user settings, edit file associations.
e.g:
```
    "files.associations": {
        "*.log.a.txt": "json"
    },
```

**Comment by ldd** [comment]
I've resolved this issue in the source code by adding a `strictMode` setting.

[Here's the commit](https://github.com/ldd/vscode-jq/commit/4c4eb50a7a346752110236078f61c80b4a412fe3)

I'll try to push a release tomorrow.

Thanks for the suggestion!

**Comment by ldd** [comment]
published to the store in v0.4.0!
fixed by 4c4eb50a7a346752110236078f61c80b4a412fe3

**Comment by rehangit** [comment]
Thanks a lot. It works great except a minor issue: shows an error at the beginning of second json object in the preview.

**Comment by ldd** [comment]
I can replicate it. A potential fix is to just hide all warnings on the editor somehow. A better fix would be to turn off validation on certain JSON files. I'll investigate it for sure
